import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { MapPin, Moon, BookOpen, Sparkles, Lock, Compass, Crown, Bell, LocateFixed, Sun, Shield, Flame, Heart, Feather } from 'lucide-react';
import './styles.css';

const planets = {
  Sun:{symbol:'☉', icon:Sun, tone:'Vitality • Confidence • Visibility', herb:'Rosemary', candle:'Gold', psalm:'Psalm 19', message:'Step into the light without performing for approval.', action:'Take one visible action before sunset.'},
  Moon:{symbol:'☽', icon:Moon, tone:'Emotion • Intuition • Memory', herb:'Mugwort', candle:'White', psalm:'Psalm 4', message:'Your feelings are information, not a sentence.', action:'Name the feeling before you react.'},
  Mars:{symbol:'♂', icon:Flame, tone:'Courage • Boundaries • Protection', herb:'Cayenne', candle:'Red', psalm:'Psalm 35', message:'Heat becomes power when you give it direction.', action:'Choose one boundary and honor it.'},
  Mercury:{symbol:'☿', icon:Feather, tone:'Clarity • Messages • Decisions', herb:'Peppermint', candle:'Yellow', psalm:'Psalm 119', message:'Your words are keys. Use them carefully.', action:'Write the message before you send it.'},
  Jupiter:{symbol:'♃', icon:Crown, tone:'Favor • Wisdom • Expansion', herb:'Cinnamon', candle:'Purple', psalm:'Psalm 65', message:'Expansion needs wisdom so blessing can stay.', action:'Ask for the door and the discipline.'},
  Venus:{symbol:'♀', icon:Heart, tone:'Love • Beauty • Softness', herb:'Rose', candle:'Pink', psalm:'Psalm 45', message:'Soften without abandoning yourself.', action:'Do one thing that restores your worth.'},
  Saturn:{symbol:'♄', icon:Shield, tone:'Structure • Endings • Protection', herb:'Comfrey', candle:'Black', psalm:'Psalm 91', message:'What feels heavy may be asking for structure.', action:'Release one thing that keeps draining you.'}
};
const order=['Saturn','Jupiter','Mars','Sun','Venus','Mercury','Moon'];
const dayRulers=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn'];
const moods=['calm','drained','anxious','hopeful','angry','open'];
const phases=['New Moon','Waxing Moon','Full Moon','Waning Moon'];
function currentPlanet(){const n=new Date(); const d=dayRulers[n.getDay()]; return order[(order.indexOf(d)+n.getHours())%7];}
function hourList(count=12){const n=new Date(); const d=dayRulers[n.getDay()]; const start=order.indexOf(d); return Array.from({length:count},(_,i)=>order[(start+i)%7]);}
function Onboarding({onDone}){const [city,setCity]=useState('');return <div className="onboard"><div className="sigil">✦</div><h1>Viriditas Hora</h1><p className="tag">The Living Power of the Hour</p><div className="moonOrb"><span>☽</span></div><p className="soft">To calculate your true planetary hours, the app needs your location for sunrise and sunset.</p><button className="primary" onClick={()=>onDone(city||'Current Location')}><LocateFixed size={18}/> Use my location</button><div className="inputWrap"><MapPin size={17}/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Or enter city, state" /></div><button className="ghost" onClick={()=>onDone(city||'Houston, TX')}>Continue</button></div>}
function Home({tier,setTier,location}){const pName=useMemo(currentPlanet,[]); const p=planets[pName]; const Icon=p.icon; const [mood,setMood]=useState('');return <div className="screen"><div className="topbar"><div><p className="over">Viriditas Hora</p><h2>Current Energy</h2></div><button className="pill"><MapPin size={14}/>{location}</button></div><section className="hero"><div className="halo"><span>{p.symbol}</span></div><p className="over">Ruling Now</p><h1>{pName} Hour</h1><p className="tone">{p.tone}</p><p className="message">“{p.message}”</p></section><section className="oneCard"><p className="label">Today’s alignment</p><div className="alignGrid"><div><small>Psalm</small><b>{p.psalm}</b></div><div><small>Herb</small><b>{p.herb}</b></div><div><small>Candle</small><b>{p.candle}</b></div></div><p className="practice">{p.action}</p></section><section><p className="sectionTitle">How does your energy feel?</p><div className="moods">{moods.map(x=><button className={mood===x?'active':''} onClick={()=>setMood(x)} key={x}>{x}</button>)}</div>{mood&&<div className="journalMini">Journal: Where did <b>{mood}</b> show up in your body today?</div>}</section><section className="upgrade"><div><p className="over">{tier}</p><h3>{tier==='Free'?'Unlock the deeper hour meaning':'Current tier active'}</h3><p>{tier==='Free'?'Seeker opens all 24 hours, herbs, crystals, oils, and healing prompts.':'Initiate adds personal patterns, sacred names, and monthly reports.'}</p></div><button onClick={()=>setTier(tier==='Free'?'Seeker':'Initiate')}>{tier==='Free'?'Upgrade':'Preview'}<Lock size={14}/></button></section></div>}
function Hora({tier}){const list=hourList(tier==='Free'?12:24);return <div className="screen"><div className="pageHead"><p className="over">Hora</p><h2>{tier==='Free'?'12 Hour Flow':'24 Hour Flow'}</h2><p>Move with the ruling current instead of fighting it.</p></div><div className="hourWheel">{list.map((x,i)=><div className="hourRow" key={i}><div className="planetMark">{planets[x].symbol}</div><div><b>{x}</b><span>{planets[x].tone}</span></div><em>{String(i).padStart(2,'0')}:00</em></div>)}</div>{tier==='Free'&&<div className="locked"><Lock size={16}/> Seeker unlocks the full 24-hour flow and rituals.</div>}</div>}
function MoonTab({tier}){return <div className="screen"><div className="pageHead"><p className="over">Moon</p><h2>Lunar Field</h2><p>The moon shows the emotional weather moving through the day.</p></div><div className="moonBig">☽</div><div className="phaseCard"><small>Current Phase</small><h1>{phases[new Date().getDate()%4]}</h1><p>Release noise. Listen inward. Let your emotions reveal what needs care.</p></div>{tier==='Free'?<div className="locked"><Lock size={16}/> Seeker unlocks lunar herbs, oils, and moon journal prompts.</div>:<div className="ritual"><b>Moon Practice</b><p>Light a white candle, breathe slowly, and write what your spirit has been trying to say quietly.</p></div>}</div>}
function Journal(){return <div className="screen"><div className="pageHead"><p className="over">Journal</p><h2>Energy Record</h2><p>Track what repeats until the pattern speaks.</p></div><div className="prompts"><div>What energy did I notice today?</div><div>What drained me?</div><div>What restored me?</div></div><textarea placeholder="Write your energetic reflection..."/></div>}
function Profile({tier,setTier}){return <div className="screen"><div className="pageHead"><p className="over">Path</p><h2>Your Energy Path</h2><p>Awareness → understanding → healing → protection → control → utilization.</p></div>{['Free','Seeker','Initiate'].map(t=><button key={t} onClick={()=>setTier(t)} className={'tier '+(tier===t?'chosen':'')}><div><b>{t}</b><span>{t==='Free'?'Awareness':t==='Seeker'?'Understanding + Healing':'Protection + Mastery'}</span></div><Crown size={18}/></button>)}</div>}
function App(){const [ready,setReady]=useState(localStorage.vhLoc?true:false); const [location,setLocation]=useState(localStorage.vhLoc||'Houston, TX'); const [tab,setTab]=useState('home'); const [tier,setTier]=useState('Free'); function done(loc){localStorage.vhLoc=loc;setLocation(loc);setReady(true)} if(!ready)return <main className="phone"><Onboarding onDone={done}/></main>; const tabs=[['home','Hora',Sparkles],['hours','Hours',Compass],['moon','Moon',Moon],['journal','Journal',BookOpen],['path','Path',Crown]];return <main className="phone"><div className="appShell">{tab==='home'&&<Home tier={tier} setTier={setTier} location={location}/>} {tab==='hours'&&<Hora tier={tier}/>} {tab==='moon'&&<MoonTab tier={tier}/>} {tab==='journal'&&<Journal/>} {tab==='path'&&<Profile tier={tier} setTier={setTier}/>}<nav>{tabs.map(([id,label,Icon])=><button className={tab===id?'on':''} onClick={()=>setTab(id)} key={id}><Icon size={19}/><span>{label}</span></button>)}</nav></div></main>}

createRoot(document.getElementById('root')).render(<App/>);
